# Generated by Django 4.1 on 2022-08-04 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updatedb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artifact_sets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('piece_2', models.CharField(max_length=100)),
                ('piece_4', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Bow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('atk', models.CharField(max_length=15)),
                ('stat', models.CharField(max_length=50)),
                ('ability', models.CharField(max_length=1500)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Catalyst',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('atk', models.CharField(max_length=15)),
                ('stat', models.CharField(max_length=50)),
                ('ability', models.CharField(max_length=1500)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Claymore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('atk', models.CharField(max_length=15)),
                ('stat', models.CharField(max_length=50)),
                ('ability', models.CharField(max_length=1500)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Polearm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('atk', models.CharField(max_length=15)),
                ('stat', models.CharField(max_length=50)),
                ('ability', models.CharField(max_length=1500)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('atk', models.CharField(max_length=15)),
                ('stat', models.CharField(max_length=50)),
                ('ability', models.CharField(max_length=1500)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
