# Generated by Django 4.1 on 2022-08-04 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updatedb', '0002_artifact_sets_bow_catalyst_claymore_polearm_sword'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artifact_set',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('piece_2', models.CharField(max_length=100)),
                ('piece_4', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Artifact_sets',
        ),
    ]
