# Generated by Django 4.1 on 2022-08-09 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updatedb', '0004_remove_character_image_alter_bow_ability_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weapons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=15)),
                ('atk', models.CharField(max_length=15)),
                ('stat', models.CharField(max_length=50)),
                ('ability', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Bow',
        ),
        migrations.DeleteModel(
            name='Catalyst',
        ),
        migrations.DeleteModel(
            name='Claymore',
        ),
        migrations.DeleteModel(
            name='Polearm',
        ),
        migrations.DeleteModel(
            name='Sword',
        ),
    ]
