# Generated by Django 4.1 on 2022-08-09 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presets', '0021_preset_character_preset_weapon'),
        ('updatedb', '0005_weapons_delete_bow_delete_catalyst_delete_claymore_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Weapons',
            new_name='Weapon',
        ),
    ]
