# Generated by Django 4.1 on 2022-08-06 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('updatedb', '0004_remove_character_image_alter_bow_ability_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main', models.CharField(max_length=25, null=True)),
                ('first', models.CharField(max_length=25, null=True)),
                ('second', models.CharField(max_length=25, null=True)),
                ('third', models.CharField(max_length=25, null=True)),
                ('fourth', models.CharField(max_length=25, null=True)),
                ('set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='updatedb.artifact_set')),
            ],
        ),
    ]
