# Generated by Django 4.1 on 2022-08-06 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('updatedb', '0004_remove_character_image_alter_bow_ability_and_more'),
        ('presets', '0003_remove_artifact_set'),
    ]

    operations = [
        migrations.AddField(
            model_name='artifact',
            name='set',
            field=models.ForeignKey(default=23, on_delete=django.db.models.deletion.CASCADE, to='updatedb.artifact_set'),
        ),
    ]
