# Generated by Django 4.1 on 2022-08-06 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presets', '0004_artifact_set'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artifact',
            old_name='first',
            new_name='stat',
        ),
        migrations.RemoveField(
            model_name='artifact',
            name='fourth',
        ),
        migrations.RemoveField(
            model_name='artifact',
            name='main',
        ),
        migrations.RemoveField(
            model_name='artifact',
            name='second',
        ),
        migrations.RemoveField(
            model_name='artifact',
            name='third',
        ),
    ]
