# Generated by Django 4.1 on 2022-08-07 12:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('updatedb', '0004_remove_character_image_alter_bow_ability_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('presets', '0005_rename_first_artifact_stat_remove_artifact_fourth_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artifact',
            old_name='stat',
            new_name='first',
        ),
        migrations.AddField(
            model_name='artifact',
            name='fourth',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='artifact',
            name='main',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='artifact',
            name='second',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='artifact',
            name='third',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='preset',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='artifact',
            name='set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='updatedb.artifact_set'),
        ),
    ]
