# Generated by Django 4.1 on 2022-08-07 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presets', '0006_rename_stat_artifact_first_artifact_fourth_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artifact',
            name='first',
        ),
        migrations.RemoveField(
            model_name='artifact',
            name='fourth',
        ),
        migrations.RemoveField(
            model_name='artifact',
            name='main',
        ),
        migrations.RemoveField(
            model_name='artifact',
            name='second',
        ),
        migrations.RemoveField(
            model_name='artifact',
            name='set',
        ),
        migrations.RemoveField(
            model_name='artifact',
            name='third',
        ),
        migrations.RemoveField(
            model_name='preset',
            name='author',
        ),
        migrations.RemoveField(
            model_name='preset',
            name='fifth_art',
        ),
        migrations.RemoveField(
            model_name='preset',
            name='first_art',
        ),
        migrations.RemoveField(
            model_name='preset',
            name='fourth_art',
        ),
        migrations.RemoveField(
            model_name='preset',
            name='name',
        ),
        migrations.RemoveField(
            model_name='preset',
            name='second_art',
        ),
        migrations.RemoveField(
            model_name='preset',
            name='third_art',
        ),
    ]
