# Generated by Django 4.1 on 2022-08-07 13:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('updatedb', '0004_remove_character_image_alter_bow_ability_and_more'),
        ('presets', '0007_remove_artifact_first_remove_artifact_fourth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artifact',
            name='first',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='artifact',
            name='fourth',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='artifact',
            name='main',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='artifact',
            name='second',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='artifact',
            name='set',
            field=models.ForeignKey(default=27, on_delete=django.db.models.deletion.CASCADE, to='updatedb.artifact_set'),
        ),
        migrations.AddField(
            model_name='artifact',
            name='third',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='preset',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='preset',
            name='name',
            field=models.CharField(default='Name', max_length=65),
        ),
    ]
