# Generated by Django 4.1 on 2022-08-07 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('updatedb', '0004_remove_character_image_alter_bow_ability_and_more'),
        ('presets', '0009_artifact_test_alter_artifact_set_alter_preset_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artifact',
            name='test',
        ),
        migrations.AddField(
            model_name='preset',
            name='fifth_stat',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='preset',
            name='first_stat',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='preset',
            name='fourth_stat',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='preset',
            name='second_stat',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='preset',
            name='third_stat',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='artifact',
            name='first',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='first', to='presets.preset'),
        ),
        migrations.AlterField(
            model_name='artifact',
            name='fourth',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='fourth', to='presets.preset'),
        ),
        migrations.AlterField(
            model_name='artifact',
            name='main',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='main', to='presets.preset'),
        ),
        migrations.AlterField(
            model_name='artifact',
            name='second',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='second', to='presets.preset'),
        ),
        migrations.AlterField(
            model_name='artifact',
            name='set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='set', to='updatedb.artifact_set'),
        ),
        migrations.AlterField(
            model_name='artifact',
            name='third',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='third', to='presets.preset'),
        ),
    ]
