# Generated by Django 4.1 on 2022-08-07 15:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('updatedb', '0004_remove_character_image_alter_bow_ability_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('presets', '0011_remove_preset_fifth_stat_remove_preset_first_stat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artifact',
            name='first',
        ),
        migrations.RemoveField(
            model_name='artifact',
            name='fourth',
        ),
        migrations.RemoveField(
            model_name='artifact',
            name='main',
        ),
        migrations.RemoveField(
            model_name='artifact',
            name='second',
        ),
        migrations.RemoveField(
            model_name='artifact',
            name='third',
        ),
        migrations.RemoveField(
            model_name='preset',
            name='art',
        ),
        migrations.AddField(
            model_name='artifact',
            name='stat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='stat', to='presets.preset'),
        ),
        migrations.AddField(
            model_name='preset',
            name='fifth_stat',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='preset',
            name='first_stat',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='preset',
            name='fourth_stat',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='preset',
            name='second_stat',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='preset',
            name='third_stat',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='artifact',
            name='set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='set', to='updatedb.artifact_set'),
        ),
        migrations.AlterField(
            model_name='preset',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
