# Generated by Django 4.1 on 2022-08-07 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presets', '0012_remove_artifact_first_remove_artifact_fourth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artifact',
            name='status',
            field=models.CharField(choices=[('bad', 'bad'), ('placeholder', 'placeholder'), ('good', 'good')], max_length=50, null=True),
        ),
    ]
