# Generated by Django 4.1 on 2022-08-07 18:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('presets', '0014_artifact_art_alter_artifact_stat'),
    ]

    operations = [
        migrations.AddField(
            model_name='artifact',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='artifact',
            name='name',
            field=models.CharField(default='artifact', max_length=65),
        ),
    ]
