# Generated by Django 4.1 on 2022-08-07 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presets', '0015_artifact_author_artifact_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artifact',
            name='name',
        ),
        migrations.AlterField(
            model_name='preset',
            name='name',
            field=models.CharField(default='Preset', max_length=65, null=True),
        ),
    ]
