# Generated by Django 4.1 on 2022-08-07 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presets', '0016_remove_artifact_name_alter_preset_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artifact',
            old_name='stat',
            new_name='first',
        ),
        migrations.AddField(
            model_name='artifact',
            name='fourth',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='artifact',
            name='main',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='artifact',
            name='second',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='artifact',
            name='third',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
