# Generated by Django 4.1 on 2022-08-08 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('presets', '0017_rename_stat_artifact_first_artifact_fourth_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artifact',
            name='art',
        ),
        migrations.AddField(
            model_name='artifact',
            name='preset',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='preset', to='presets.preset'),
        ),
        migrations.AlterField(
            model_name='preset',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='preset',
            name='name',
            field=models.CharField(max_length=65, null=True),
        ),
    ]
