# Generated by Django 4.1 on 2022-08-09 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presets', '0019_alter_artifact_first_alter_artifact_fourth_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preset',
            name='fifth_stat',
        ),
        migrations.RemoveField(
            model_name='preset',
            name='first_stat',
        ),
        migrations.RemoveField(
            model_name='preset',
            name='fourth_stat',
        ),
        migrations.RemoveField(
            model_name='preset',
            name='second_stat',
        ),
        migrations.RemoveField(
            model_name='preset',
            name='third_stat',
        ),
        migrations.AlterField(
            model_name='artifact',
            name='first',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='artifact',
            name='fourth',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='artifact',
            name='main',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='artifact',
            name='second',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='artifact',
            name='third',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
