# Generated by Django 4.1 on 2022-08-09 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('updatedb', '0005_weapons_delete_bow_delete_catalyst_delete_claymore_and_more'),
        ('presets', '0020_remove_preset_fifth_stat_remove_preset_first_stat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='preset',
            name='character',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='updatedb.character'),
        ),
        migrations.AddField(
            model_name='preset',
            name='weapon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='updatedb.weapons'),
        ),
    ]
