# Generated by Django 4.1 on 2022-08-09 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presets', '0021_preset_character_preset_weapon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artifact',
            name='first',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='artifact',
            name='fourth',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='artifact',
            name='main',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='artifact',
            name='second',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='artifact',
            name='third',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
