# Generated by Django 4.1 on 2022-08-13 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('updatedb', '0006_rename_weapons_weapon'),
        ('presets', '0022_alter_artifact_first_alter_artifact_fourth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artifact',
            name='set',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='set', to='updatedb.artifact_set'),
        ),
        migrations.AlterField(
            model_name='artifact',
            name='status',
            field=models.CharField(blank=True, choices=[('bad', 'bad'), ('placeholder', 'placeholder'), ('good', 'good')], max_length=50, null=True),
        ),
    ]
